export default {
    electricity: [
        {
            period: '03.2018',
            fio: 'Литвиненко Александр Юрьевич',
            address: 'ул. Ленина д. 20',
            startKwh: '588.797',
            expenseKwh: '0.425',
            finishKwh: '589.222',
            price: '1.25',
            checkoutPrice: '321.23',
        },
        {
            period: '03.2018',
            fio: 'Литвиненко Александр Юрьевич',
            address: 'пр. Победы д. 30',
            startKwh: '1.797',
            expenseKwh: '0.225',
            finishKwh: '2.022',
            price: '1.25',
            checkoutPrice: '2.50',
        },
        {
            period: '02.2018',
            fio: 'Литвиненко Александр Юрьевич',
            address: 'ул. Ленина д. 20',
            startKwh: '588.797',
            expenseKwh: '0.425',
            finishKwh: '589.222',
            price: '1.25',
            checkoutPrice: '221.23',
        },
        {
            period: '01.2018',
            fio: 'Литвиненко Александр Юрьевич',
            address: 'ул. Ленина д. 20',
            startKwh: '588.797',
            expenseKwh: '0.425',
            finishKwh: '589.222',
            price: '1.25',
            checkoutPrice: '421.23',
        },
        {
            period: '12.2017',
            fio: 'Литвиненко Александр Юрьевич',
            address: 'ул. Ленина д. 20',
            startKwh: '528.712',
            expenseKwh: '0.325',
            finishKwh: '529.222',
            price: '1.25',
            checkoutPrice: '121.23',
        }
    ],
    users: [
        {
            id: 1,
            name: 'Logan Schowalter',
            role: 'admin',
        },
        {
            id: 2,
            name: 'Breanna Gibson',
            role: 'user',
        },
        {
            id: 3,
            name: 'Annamarie Mayer',
            role: 'user',
        },
    ],
};
